### ISSUE TITLE
Why "y" is reserved_name?

### ISSUE THREAD

**Issue by diota** [AaronLasseigne/active_interaction#444]
```ruby
class PlacingSomething < ActiveInteraction::Base
     float :x
     float :y
     file :image
     

     def execute
        #place image to x, y location
     end

end
```

`PlacingSomething.run(x: 1.2, y: 0.2, image: 'lots_of_soothing_puppies.jpg')`
throws error of [:y => 'is required']

`ActiveInteraction::InvalidFilterError (“y” is a reserved name)`

when put `self.y` inside the code, I got 
`NoMethodError: private method 'y' called for #<PlacingSomething:0x00000000020383b8>`

**Comment by antulik** [comment]
Could not reproduce the issue on v3.6.2

```ruby
class PlacingSomething < ActiveInteraction::Base
  float :x
  float :y

  def execute
    self.y
  end
end

puts PlacingSomething.run!(x: 1.2, y: 0.2)
```
@diota perhaps some gem or extension messing it up?

**Comment by diota** [comment]
I'm using Rails v2.4.4

`rails new placement_app`

add `gem 'active_interaction', '~> 3.6.2'` inside the Gemfile

and I put _your codes_ inside app/services/placing_something.rb

`rails c`
```ruby
Running via Spring preloader in process 19963
Loading development environment (Rails 5.2.1)
irb(main):001:0> puts PlacingSomething.run!(x: 1.2, y: 0.2)
ActiveInteraction::InvalidFilterError: "y" is a reserved name
	from app/services/placing_something.rb:4:in `<class:PlacingSomething>'
	from app/services/placing_something.rb:2:in `<main>'
	from (irb):1
irb(main):002:0> 
```

**Comment by antulik** [comment]
As it turns out it all depends when you load the the class. 

`psych` gem defines global `y` method. ActiveInteraction does not allow filters that overwrite methods on `Base` class. So if the `psych` gem is loaded before, active interaction will complain. 

```ruby
[2] pry(main)> method(:y).source_location
=> ["/Users/anton/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych/y.rb", 5]
```
https://github.com/ruby/psych/blob/master/lib/psych/y.rb#L5

I was running script with rails runner `rails r /file/path` and surprisingly it was working correctly, but I'm getting the error if running in console.

**Comment by AaronLasseigne** [comment]
Yup, we try to avoid collisions that may arrive when people accidentally override internal methods with filters.
