### ISSUE TITLE
Error with inputs method after 4.0 release

### ISSUE THREAD

**Issue by spencersteiner** [AaronLasseigne/active_interaction#493]
Hey there! Thanks for your awesome work on this project, I absolutely love using this library.

I noticed my tests started breaking today (I've been using the v4.0.0 tag for a number of months) and I'm getting the following error: 
``` ruby
inputs must be a hash or ActionController::Parameters
```

I wasn't sure if it was just my app or configuration, so I created a fresh new rails environment using ruby 2.6 and Rails 6. I created your `Add` and `AddAndDouble` classes from the readme examples, and got the same error for the line `compose(Add, inputs) * 2` when calling `AddAndDouble.run!(x: 1, y: 1)`

I also noticed the release notes mention a change to [inputs](https://github.com/AaronLasseigne/active_interaction/releases/tag/v4.0.0) and wasn't sure if that is related to this.

Do I need to be handling inputs differently for 4.0, or is this a bug?

**Comment by VetLee** [comment]
A similar problem. Temporarily used `inputs.to_h`

**Comment by spencersteiner** [comment]
@VetLee Glad I'm not the only one! I'm converting the inputs to hash just as you are for the time being.

**Comment by AaronLasseigne** [comment]
My environment here is slightly different but it's close and it looks like it works fine:

<img width="482" alt="CleanShot 2021-04-03 at 17 05 35@2x" src="https://user-images.githubusercontent.com/297205/113492681-d7ba8180-949e-11eb-8742-31417a11f39c.png">

Can you give me a better understanding of what you're doing to cause it to fail?

**Comment by spencersteiner** [comment]
@AaronLasseigne Ah, I could have been clearer: the issue pertains to the `inputs` hash specifically. Referencing the individual inputs by name works fine. Are you able to replicate with the example code like I have below? (I executed in a rails 6.0.3.6 environment). 

I'm also happy to create a repo with a clean rails environment where it can be replicated if that's preferable!

![Screen Shot 2021-04-05 at 1 45 30 PM](https://user-images.githubusercontent.com/6234219/113618669-3c97e800-9615-11eb-9f10-6ea700b09fe7.png)

**Comment by gblair** [comment]
Just chiming in because I noticed (I think) this same issue today after upgrading to the latest version. 

It looks like the type returned from the `inputs` method inside an interaction is `ActiveInteraction::Inputs` which tosses an error in `ActiveInteraction::Base#normalize_inputs!`:

```ruby
def normalize_inputs!(inputs)
  return inputs if inputs.is_a?(Hash)

  parameters = 'ActionController::Parameters'
  klass = parameters.safe_constantize
  return inputs.to_unsafe_h if klass && inputs.is_a?(klass)

  raise ArgumentError, "inputs must be a hash or #{parameters}"
end
```

This is a problem when using the `inputs` method inside an interaction to share inputs with a composed interaction.  For now, rather than rewriting all my `compose` calls with `inputs.to_h` I'm just rolling back to `3.8.3`. I could hazard a PR for this, if you just want to allowlist the `ActiveInteraction::Inputs` as well -- just say the word!
